[package]
name = "hyper-tls"
version = "0.0.0"
description = "Default TLS implementation for use with hyper"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
license = "MIT/Apache-2.0"
keywords = ["hyper", "tls", "http", "https", "ssl"]
repository = "https://github.com/hyperium/hyper-tls"
documentation = "https://docs.rs/hyper-tls"

[dependencies]
futures = "0.1.11"
native-tls = "0.1"
hyper= { path = "../hyper", version = "0.11.0-a.0" }
tokio-core = "0.1.6"
tokio-io = "0.1"
tokio-service = "0.1"
tokio-tls = "0.1.2"
