[package]

name = "hyper"
version = "0.11.0-a.0"
description = "A modern HTTP library."
readme = "README.md"
documentation = "http://hyperium.github.io/hyper"
repository = "https://github.com/hyperium/hyper"
license = "MIT"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
keywords = ["http", "hyper", "hyperium"]
categories = ["web-programming::http-client", "web-programming::http-server"]
build = "build.rs"

include = [
  "build.rs",
  "Cargo.toml",
  "LICENSE",
  "src/**/*"
]

[dependencies]
base64 = "0.4"
bytes = "0.4"
futures = "0.1.11"
futures-cpupool = "0.1"
httparse = "1.0"
language-tags = "0.2"
log = "0.3"
mime = "0.2"
time = "0.1"
tokio-core = "0.1.6"
tokio-proto = "0.1"
tokio-service = "0.1"
tokio-io = "0.1"
unicase = "1.0"
url = "1.0"

[dev-dependencies]
num_cpus = "1.0"
pretty_env_logger = "0.1"
spmc = "0.2"

[build-dependencies]
rustc_version = "0.1"

[features]
default = []
nightly = []
